[book]
title = "stacy - Modern Stata Workflow Tool"
authors = ["Jan Fasnacht"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/janfasnacht/stacy"
edit-url-template = "https://github.com/janfasnacht/stacy/edit/main/docs/src/{path}"
site-url = "https://stacy.janfasnacht.com/"
default-theme = "light"
preferred-dark-theme = "ayu"
smart-punctuation = true

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
use-boolean-and = true
